inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-minitest

AllCops:
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "**/tmp/**/*"
    - "**/vendor/**/*"
    - bench/**/*
    - bin/**/*
    - db/*schema.rb
    - lib/generators/**/*schema.rb
    - gemfiles/*
    - test/**/*schema.rb
    - Gemfile.lock
  TargetRubyVersion: 3.2

Layout/AccessModifierIndentation:
  Enabled: true

Layout/DefEndAlignment:
  Enabled: true

Layout/EmptyLineAfterMagicComment:
  Enabled: true

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: indented_internal_methods

Layout/InitialIndentation:
  Enabled: true

Minitest:
  Enabled: true

Minitest/MultipleAssertions:
  Enabled: false

Performance:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
